export const ADD_DRAFT = 'ADD_DRAFT';
export const ADD_NOTE = 'ADD_NOTE';
export const EDIT_NOTE = 'EDIT_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const SET_SELECTED_NOTE = 'SET_SELECTED_NOTE';
export const UPDATE_NOTE_PREVIEW = 'UPDATE_NOTE_PREVIEW';
export const APPEND_NOTE_PREVIEW = 'APPEND_NOTE_PREVIEW';
export const SLICE_NOTE_PREVIEW = 'SLICE_NOTE_PREVIEW';
export const TRANSFER_NOTE = 'TRANSFER_NOTE';
export const SYNC_NOTES = 'SYNC_NOTES';
export const CLEAR_BIN = 'CLEAR_BIN';

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const TOGGLE_VISIBILITY_FILTER = 'TOGGLE_VISIBILITY_FILTER';

export const ADD_DRAGGABLE = 'ADD_DRAGGABLE';
export const TRANSLATE_DRAGGABLE = 'TRANSLATE_DRAGGABLE';
export const SET_DRAGGABLE_IS_MOVING = 'SET_DRAGGABLE_IS_MOVING';
export const SET_DRAGGABLE_MOUSE_POSITION = 'SET_DRAGGABLE_MOUSE_POSITION';
